# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170307_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Текст комментария:'),
        ),
    ]
