# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20170508_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
